spring.application.name=AssetInspection
spring.jpa.show-sql=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.config.import=optional:configserver:http://localhost:8888

# Retry configuration
resilience4j.retry.instances.AssetInspection-Service.max-attempts=5
resilience4j.retry.instances.AssetInspection-Service.wait-duration=2s